import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F5FCFF",
    alignItems: "center",
    justifyContent: "center",
  },
  navButtonExatas: {
    marginLeft: 12,
    width: 390,
    marginTop: 20,
    padding: 20,
    marginBottom: 10,
    alignItems: "center",
    margin: "auto",
    backgroundColor: "#f0d807",
    color: "black",
  },
  navButtonHumanas: {
    marginLeft: 12,
    width: 390,
    marginTop: 20,
    padding: 20,
    marginBottom: 10,
    alignItems: "center",
    margin: "auto",
    backgroundColor: "#de1818",
    color: "black",
  },
  navButtonLinguagens: {
    marginLeft: 12,
    width: 390,
    marginTop: 20,
    padding: 20,
    marginBottom: 10,
    alignItems: "center",
    margin: "auto",
    backgroundColor: "#0f85d9",
    color: "black",
  },
  navButton: {
    marginLeft: 12,
    width: 390,
    marginTop: 20,
    padding: 20,
    marginBottom: 10,
    alignItems: "center",
    margin: "auto",
    backgroundColor: "#002147",
    color: "black",
  },
  imgPrincipal: {
    width: 380,
    height: 210,
    marginTop: 55,
    margin: "auto",
    marginLeft: 15,
  },
  textPrincipal: {
    fontSize: 30,
    marginBottom: 70,
    marginTop: 15,
    textAlign: "center",
  },
  text: {
    fontSize: 15,
    lineHeight: 30,
    justifyContent: "center",
    marginTop: -70,
    padding: 23,
  },
  textCategorias: {
    fontSize: 20,
    marginBottom: 70,
    marginTop: 15,
    textAlign: "center",
  },
  imgLinguagens: {
    width: 350,
    height: 210,
  },
  scroll: {
    margin: 0,
  },
  textCategoriasCard: {
    fontSize: 20,
    color: "white",
    marginTop: 15,
    textAlign: "center",
  },
});
export default styles;
